name: chulla_cash
description: "The only app that gets your money into shape Manage money on the go in the app"
publish_to: 'Playstore and Appstore'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  #splash screen
  flutter_native_splash: ^2.4.0
  #firebasecore
  firebase_core: ^2.20.0
  #firebase auth
  firebase_auth: ^4.20.0
  #firebase storage
  firebase_storage: ^11.2.0
  #firebase firestore
  cloud_firestore: ^4.10.0
  #getX
  get: ^4.6.6
  #idioma
  intl: 0.19.0
  #flutter localizations
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  #icons
  flutter_launcher_icons: ^0.14.2
  flutter_gen_runner: ^5.8.0


#icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/icon.jpg"
  min_sdk_android: 21

#splash screen
flutter_native_splash:
  image: lib/assets/icons/icon.jpg
  color: "#FFFFFF"
  fullscreen: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/icons/ icon_removebg.png